"""add video_call_link to appointment

Revision ID: 405283716bdb
Revises: a59f50813f24
Create Date: 2026-01-13 23:26:03.291114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405283716bdb'
down_revision: Union[str, Sequence[str], None] = 'a59f50813f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('video_call_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'video_call_link')
    # ### end Alembic commands ###
