"""add appointment_type to appointment

Revision ID: 6c2eee6ee764
Revises: 405283716bdb
Create Date: 2026-01-13 23:37:51.096603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2eee6ee764'
down_revision: Union[str, Sequence[str], None] = '405283716bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_type')
    # ### end Alembic commands ###
