"""add clinic_address and phone_number to doctor

Revision ID: a2c07bda8c35
Revises: 6c2eee6ee764
Create Date: 2026-01-14 00:10:17.899449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c07bda8c35'
down_revision: Union[str, Sequence[str], None] = '6c2eee6ee764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('clinic_address', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'phone_number')
    op.drop_column('doctors', 'clinic_address')
    # ### end Alembic commands ###
